### ISSUE TITLE
Errors while attempting to extract data with xtractomatic

### ISSUE THREAD

**Issue by lhg2993** [rmendels/xtractomatic#2]
Hello,

I'm trying to extract chlorophyll A data from the dataset Chlorophyll-a, Aqua MODIS, NPP, Pacific Ocean (1 Day Composite) using xtracto. I've made sure that my dates and coordinates are within the ones of this dataset, but it doesn't work. When entering a big list of coordinates and dates, I get the following errors:
> clorofila<-xtracto('mbchla1day', PD$LongDecimal_INICAL, PD$LatDecimal_INICAL, PD$FECHA, xlen=0, ylen=0, verbose=FALSE)
[1] "Error trying to retrive file, status500"
[1] "Header Info of URL Request"
[1] "https://coastwatch.pfeg.noaa.gov/erddap/griddap/erdMBchla1day.nc?chlorophyll[(1.323e+09):1:(1.323e+09)][(0):1:(0)][(30.425):1:(30.425)][(243.5):1:(243.5)]"
[1] "There was an error in the url call.  See message on screen and URL called"
[1] "Returning incomplete download"

Then, I tried entering a single coordinate and date. I made sure that the date has a value for chlorophyll on the website, but I get this error:

> xtracto('mbchla1day',-115.029167,26.618333,2008-02-08,xlen=0,ylen=0,verbose=FALSE)
[1] "tpos  (time) has elements out of range of the dataset"
[1] "time range in tpos"
[1] "1975-06-22,1975-06-22"
[1] "time range in ERDDAP data"
[1] "2006-01-01,2018-01-28"
Error in xtracto("mbchla1day", -115.029167, 26.618333, 2008 - 2 - 8, xlen = 0,  : 
  Coordinates out of dataset bounds - see messages above

How can I solve this?

Thank you very much for your help.

**Comment by rmendels** [comment]
Based on the URLs you are sending me, it looks like you are running version 3.4.0.  Please install the latest version,  3.4.1,  I think it will fix your problem.  If not, please send me the first 2 or 3 data points.

-Roy

> On Jan 29, 2018, at 11:18 AM, lhg2993 <notifications@github.com> wrote:
> 
> Hello,
> 
> I'm trying to extract chlorophyll A data from the dataset Chlorophyll-a, Aqua MODIS, NPP, Pacific Ocean (1 Day Composite) using xtracto. I've made sure that my dates and coordinates are within the ones of this dataset, but it doesn't work. When entering a big list of coordinates and dates, I get the following errors:
> 
> clorofila<-xtracto('mbchla1day', PD$LongDecimal_INICAL, PD$LatDecimal_INICAL, PD$FECHA, xlen=0, ylen=0, verbose=FALSE)
> [1] "Error trying to retrive file, status500"
> [1] "Header Info of URL Request"
> [1] "https://coastwatch.pfeg.noaa.gov/erddap/griddap/erdMBchla1day.nc?chlorophyll[(1.323e+09):1:(1.323e+09)][(0):1:(0)][(30.425):1:(30.425)][(243.5):1:(243.5)]"
> [1] "There was an error in the url call. See message on screen and URL called"
> [1] "Returning incomplete download"
> 
> Then, I tried entering a single coordinate and date. I made sure that the date has a value for chlorophyll on the website, but I get this error:
> 
> xtracto('mbchla1day',-115.029167,26.618333,2008-02-08,xlen=0,ylen=0,verbose=FALSE)
> [1] "tpos (time) has elements out of range of the dataset"
> [1] "time range in tpos"
> [1] "1975-06-22,1975-06-22"
> [1] "time range in ERDDAP data"
> [1] "2006-01-01,2018-01-28"
> Error in xtracto("mbchla1day", -115.029167, 26.618333, 2008 - 2 - 8, xlen = 0, :
> Coordinates out of dataset bounds - see messages above
> 
> How can I solve this?
> 
> Thank you very much for your help.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

**********************
"The contents of this message do not reflect any position of the U.S. Government or NOAA."
**********************
Roy Mendelssohn
Supervisory Operations Research Analyst
NOAA/NMFS
Environmental Research Division
Southwest Fisheries Science Center
***Note new street address***
110 McAllister Way
Santa Cruz, CA 95060
Phone: (831)-420-3666
Fax: (831) 420-3980
e-mail: Roy.Mendelssohn@noaa.gov www: http://www.pfeg.noaa.gov/

"Old age and treachery will overcome youth and skill."
"From those who have been given much, much will be expected" 
"the arc of the moral universe is long, but it bends toward justice" -MLK Jr.

**Comment by lhg2993** [comment]
Thank you very much, I was able to extract data efficiently.
