### ISSUE TITLE
error with xtractogon

### ISSUE THREAD

**Issue by abfleishman** [rmendels/xtractomatic#3]
I am trying to extract sst from a series of polygons and I keep running into polygons that throw an error.  I have made a reproducable example:
```
temp<-structure(list(piece = c(9L, 9L, 9L, 9L, 9L, 9L), id = c("SJ_F_Feb-Apr_2015_core_9", 
"SJ_F_Feb-Apr_2015_core_9", "SJ_F_Feb-Apr_2015_core_9", "SJ_F_Feb-Apr_2015_core_9", 
"SJ_F_Feb-Apr_2015_core_9", "SJ_F_Feb-Apr_2015_core_9"), Sex = c("F", 
"F", "F", "F", "F", "F"), type = c("core", "core", "core", "core", 
"core", "core"), Island = c("SJ", "SJ", "SJ", "SJ", "SJ", "SJ"
), Season = c("Feb-Apr_2015", "Feb-Apr_2015", "Feb-Apr_2015", 
"Feb-Apr_2015", "Feb-Apr_2015", "Feb-Apr_2015"), date.min = structure(c(1L, 
1L, 1L, 1L, 1L, 1L), .Label = c("2015-01-03", "2015-09-21", "2015-12-21", 
"2016-04-30"), class = "factor"), date.max = structure(c(1L, 
1L, 1L, 1L, 1L, 1L), .Label = c("2015-04-30", "2015-12-13", "2016-01-27", 
"2016-07-09"), class = "factor"), area = c(0.207268048922507, 
0.207268048922507, 0.207268048922507, 0.207268048922507, 0.207268048922507, 
0.207268048922507), Longitude = c(-113.90585885689, -113.906338874886, 
-113.905876518658, -113.904559116132, -113.90585885689, -113.90585885689
), Latitude = c(31.3655316683359, 31.3660086691013, 31.3680647581512, 
31.3660177236027, 31.3655316683359, 31.3655316683359)), class = "data.frame", row.names = c(NA, 
-6L))


dtype<-"jplMURSST41mday"
tpos<-c("2015-01-03", "2015-04-30")

evar<-xtractogon(xpos=temp$Longitude,
                 ypos=temp$Latitude,
                 tpos=tpos,
                 dtype=dtype,verbose=TRUE)

```

> -> GET /erddap/griddap/jplMURSST41mday.nc?sst[(2015-01-16):1:(2015-04-16)][(31.37):1:(31.37)][(-113.91):1:(-113.9)] HTTP/1.1
> -> Host: coastwatch.pfeg.noaa.gov
> -> User-Agent: libcurl/7.54.0 r-curl/3.2 httr/1.3.1
> -> Accept-Encoding: gzip, deflate
> -> Accept: application/json, text/xml, application/xml, */*
> -> 
> <- HTTP/1.1 200 
> <- Date: Tue, 26 Feb 2019 04:26:11 GMT
> <- Strict-Transport-Security: max-age=31536000; includeSubDomains
> <- Last-Modified: Tue, 26 Feb 2019 04:26:11 GMT
> <- xdods-server: dods/3.7
> <- erddap-server: 1.82
> <- Content-Disposition: attachment;filename=jplMURSST41mday_44f3_f0b8_0d13.nc
> <- Content-Encoding: gzip
> <- Content-Type: application/x-netcdf
> <- Connection: close
> <- Transfer-Encoding: chunked
> <- 
> Downloading: 2.3 kB     Error in dim(in.poly) <- dim(extract$data[, , 1]) : 
>   dims [product 8] do not match the length of object [2]

I looked into the code for xtractogon and it seems like there is some rounding of the coordinates that are returned by line 27
the `ypos1` going in is `ypos1 = c(31.36553, 31.36806)` but the result of line 27 `extract$latitude` = `31.37`
Later when creating  `in.poly` the entire polygon is outside of the extracted data because of the rounding.  
I understand that this is an edge case, but I thought you might have thoughts about how to overcome this issue. 
 Thanks!!!

**Comment by rmendels** [comment]
I do not have much time to look at this in detail right now.  But a quick look at the example has the latitudes and longitudes changing less than the resolution of the data  (I may be wrong on this - as I said a quick look).  Remember wha is going on:

1. The smallest grid that contains the polygon is found.
2. That grid is downloaded
3. There is a test if any grid point is in the polygon. 
 
If the polygon is too small, then no grid point will lie in there.  

BTW - no rounding is going on in the program.  The coordinate values are what is returned by the system.  In MUR,  they are given with differing number of decimal places.  You also have to be careful when displaying number in R,  the default will not always print out the full value.

**Comment by rmendels** [comment]
@abfleishman   forgot to @ you on my response.  Check the issue page.

**Comment by abfleishman** [comment]
Thanks!  I have worked around the issue for my purpose.  But I think there is still something fishy going on.  Thanks for your response and I will close the issue
